aad

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -44,7 +44,15 @@ jobs:
         env:
           ALL_CHANGED_DOCS: ${{ steps.changed-files.outputs.all_changed_files }}
         run: |
+          
           for file in ${ALL_CHANGED_DOCS}; do
-            echo "changed file:${file}"
-            echo "changed content: $(git diff ${file})"
+            error_files=''
+            if git diff HEAD HEAD^1 ${file}|tail -n -4|grep '^+'|grep -i 'you|they' > /dev/null ; then
+              error_files+="${file}\n"
+            fi
           done
+          if [[ "x${error_files}" != "x" ]]; then
+             echo -e "In the docs we try not to use 'you' or 'they' \n${error_files}"
+             exit 1
+          fi
+        
